logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction: DEBUG

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/library
#    username: test
#    password: test
  sql:
    init:
      mode: always
