logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        transaction: DEBUG

spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/library
#    username: test
#    password: test
  sql:
    init:
      mode: always
